export default {
  AF: "Afghan",
  AX: "Åland Island",
  AL: "Albanian",
  DZ: "Algerian",
  AS: "American Samoan",
  AD: "Andorran",
  AO: "Angolan",
  AI: "Anguillan",
  AQ: "Antarctic",
  AG: "Antiguan",
  AR: "Argentine",
  AM: "Armenian",
  AW: "Aruban",
  AU: "Australian",
  AT: "Austrian",
  AZ: "Azeri",
  BS: "Bahamian",
  BH: "Bahraini",
  BD: "Bangladeshi",
  BB: "Barbadian",
  BY: "Belarusian",
  BE: "Belgian",
  BZ: "Belizean",
  BJ: "Beninois",
  BM: "Bermudian",
  BT: "Bhutanese",
  BO: "Bolivian",
  BQ: "Bonaire",
  BA: "Bosnian or Herzegovinian",
  BW: "Botswanan",
  BV: "Bouvet Island",
  BR: "Brazilian",
  IO: "BIOT",
  BN: "Bruneian",
  BG: "Bulgarian",
  BF: "Burkinabé",
  BI: "Burundian",
  CV: "Cabo Verdean",
  KH: "Cambodian",
  CM: "Cameroonian",
  CA: "Canadian",
  KY: "Caymanian",
  CF: "Central African",
  TD: "Chadian",
  CL: "Chilean",
  CN: "Chinese",
  CX: "Christmas Island",
  CC: "Cocos Island",
  CO: "Colombian",
  KM: "Comorian",
  CG: "Congolese",
  CD: "Congolese",
  CK: "Cook Island",
  CR: "Costa Rican",
  CI: "Ivorian",
  HR: "Croatian",
  CU: "Cuban",
  CW: "Curaçaoan",
  CY: "Cypriot",
  CZ: "Czech",
  DK: "Danish",
  DJ: "Djiboutian",
  DM: "Dominican",
  DO: "Dominican",
  EC: "Ecuadorian",
  EG: "Egyptian",
  SV: "Salvadoran",
  GQ: "Equatoguinean",
  ER: "Eritrean",
  EE: "Estonian",
  ET: "Ethiopian",
  FK: "Falkland Island",
  FO: "Faroese",
  FJ: "Fijian",
  FI: "Finnish",
  FR: "French",
  GF: "French Guianese",
  PF: "French Polynesian",
  TF: "French Southern Territories",
  GA: "Gabonese",
  GM: "Gambian",
  GE: "Georgian",
  DE: "German",
  GH: "Ghanaian",
  GI: "Gibraltar",
  GR: "Greek",
  GL: "Greenlandic",
  GD: "Grenadian",
  GP: "Guadeloupe",
  GU: "Guamanian",
  GT: "Guatemalan",
  GG: "Channel Island",
  GN: "Guinean",
  GW: "Bissau-Guinean",
  GY: "Guyanese",
  HT: "Haitian",
  HM: "Heard Island or McDonald Islands",
  VA: "Vatican",
  HN: "Honduran",
  HK: "Hong Kongese",
  HU: "Hungarian, Magyar",
  IS: "Icelandic",
  IN: "Indian",
  ID: "Indonesian",
  IR: "Iranian",
  IQ: "Iraqi",
  IE: "Irish",
  IM: "Manx",
  IL: "Israeli",
  IT: "Italian",
  JM: "Jamaican",
  JP: "Japanese",
  JE: "Channel Island",
  JO: "Jordanian",
  KZ: "Kazakh",
  KE: "Kenyan",
  KI: "I-Kiribati",
  KP: "North Korean",
  KR: "South Korean",
  KW: "Kuwaiti",
  KG: "Kyrgyz",
  LA: "Lao, Laotian",
  LV: "Latvian",
  LB: "Lebanese",
  LS: "Basotho",
  LR: "Liberian",
  LY: "Libyan",
  LI: "Liechtenstein",
  LT: "Lithuanian",
  LU: "Luxembourgish",
  MO: "Macanese",
  MK: "Macedonian",
  MG: "Malagasy",
  MW: "Malawian",
  MY: "Malaysian",
  MV: "Maldivian",
  ML: "Malinese",
  MT: "Maltese",
  MH: "Marshallese",
  MQ: "Martiniquais",
  MR: "Mauritanian",
  MU: "Mauritian",
  YT: "Mahoran",
  MX: "Mexican",
  FM: "Micronesian",
  MD: "Moldovan",
  MC: "Monégasque",
  MN: "Mongolian",
  ME: "Montenegrin",
  MS: "Montserratian",
  MA: "Moroccan",
  MZ: "Mozambican",
  MM: "Burmese",
  NA: "Namibian",
  NR: "Nauruan",
  NP: "Nepalese",
  NL: "Dutch",
  NC: "New Caledonian",
  NZ: "New Zealand",
  NI: "Nicaraguan",
  NE: "Nigerien",
  NG: "Nigerian",
  NU: "Niuean",
  NF: "Norfolk Island",
  MP: "Northern Marianan",
  NO: "Norwegian",
  OM: "Omani",
  PK: "Pakistani",
  PW: "Palauan",
  PS: "Palestinian",
  PA: "Panamanian",
  PG: "Papua New Guinean",
  PY: "Paraguayan",
  PE: "Peruvian",
  PH: "Philippine, Filipino",
  PN: "Pitcairn Island",
  PL: "Polish",
  PT: "Portuguese",
  PR: "Puerto Rican",
  QA: "Qatari",
  RE: "Réunionese",
  RO: "Romanian",
  RU: "Russian",
  RW: "Rwandan",
  BL: "Barthélemois",
  SH: "Saint Helenian",
  KN: "Kittitian",
  LC: "Saint Lucian",
  MF: "Saint-Martinoise",
  PM: "Saint-Pierrais or Miquelonnais",
  VC: "Vincentian",
  WS: "Samoan",
  SM: "Sammarinese",
  ST: "São Toméan",
  SA: "Arabian",
  SN: "Senegalese",
  RS: "Serbian",
  SC: "Seychellois",
  SL: "Sierra Leonean",
  SG: "Singaporean",
  SX: "Sint Maarten",
  SK: "Slovak",
  SI: "Slovenian",
  SB: "Solomon Island",
  SO: "Somalian",
  ZA: "South African",
  GS: "South Georgian",
  SS: "South Sudanese",
  ES: "Spanish",
  LK: "Sri Lankan",
  SD: "Sudanese",
  SR: "Surinamese",
  SJ: "Svalbard",
  SZ: "Swazi",
  SE: "Swedish",
  CH: "Swiss",
  SY: "Syrian",
  TW: "Taiwanese",
  TJ: "Tajikistani",
  TZ: "Tanzanian",
  TH: "Thai",
  TL: "Timorese",
  TG: "Togolese",
  TK: "Tokelauan",
  TO: "Tongan",
  TT: "Trinidadian",
  TN: "Tunisian",
  TR: "Turkish",
  TM: "Turkmen",
  TC: "Turks",
  TV: "Tuvaluan",
  UG: "Ugandan",
  UA: "Ukrainian",
  AE: "Emirian",
  GB: "British",
  UM: "American",
  US: "American",
  UY: "Uruguayan",
  UZ: "Uzbek",
  VU: "Vanuatuan",
  VE: "Venezuelan",
  VN: "Vietnamese",
  VG: "Virginian",
  VI: "Virginian",
  WF: "Wallis",
  EH: "Sahrawi",
  YE: "Yemeni",
  ZM: "Zambian",
  ZW: "Zimbabwean"
};
