const types = {
  // contacts
  GET_CONTACT_LIST: "GET_CONTACT_LIST",
  SORT_CONTACT_LIST: "SORT_CONTACT_LIST",
  GET_CONTACT_LIST_START: "GET_CONTACT_LIST_START",
  SET_DATA_VIEW: "SET_DATA_VIEW",
  SET_PAGINATION_DATA: "SET_PAGINATION_DATA",
  SET_PAGINATION_TILED_DATA: "SET_PAGINATION_TILED_DATA",
  SET_FILTER_DATA: "SET_FILTER_DATA",
  // sign in
  GET_USER_DATA: "GET_USER_DATA"
};

export default types;
